# -*- coding: utf-8 -*-
"""rotasfluviais.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xUTDhEwuLlUiIKNXFvYQ2qQz3RGOuGTg
"""

# =====================================================
# ORGANIZADOR DE ROTAS DE ENTREGA - RIO MADEIRA
# Manaus -> Nova Olinda -> Axinim -> Borba
# -> Novo Aripuanã -> Manicoré
# =====================================================

rota = [
    {
        "cidade": "Nova Olinda do Norte",
        "distancia": 234, #km
        "tempo": "12:00 horas de viagem" #hora
    },
    {
        "cidade": "Axinim",
        "distancia": 37, #km
        "tempo": "2:30 horas de viagem" #hora
    },
    {
        "cidade": "Borba",
        "distancia": 49, #km
        "tempo": "3:00 horas de viagem" #hora
    },
    {
        "cidade": "Novo Aripuanã",
        "distancia": 119, #km
        "tempo": "9:00 horas de viagem" #hora
    },
    {
        "cidade": "Manicoré",
        "distancia": 128, #km
        "tempo": "11:00 horas de viagem" #hora

    }
]

# -----------------------------------------------------
# Converte hh:mm para minutos
# -----------------------------------------------------
def converter_para_minutos(horario):
    # # Remove qualquer texto após o horário, como "horas de viagem"
    if " horas de viagem" in horario:
        time_part = horario.split(" horas de viagem")[0]
    else:
        time_part = horario # Assume que já está no formato hh:mm

    horas, minutos = time_part.split(":")

    return int(horas) * 60 + int(minutos)


# -----------------------------------------------------
# Converte minutos para hh:mm
# -----------------------------------------------------
def converter_para_horas(minutos_totais):

    horas = minutos_totais // 60
    minutos = minutos_totais % 60

    return f"{horas}h {minutos:02d}min"


# -----------------------------------------------------
# Listar rota completa
# -----------------------------------------------------
def listar_rota():

    print("\n=== ROTA FLUVIAL DO RIO MADEIRA ===")

    cidade_atual = "Manaus"

    for destino in rota:

        print(f"{cidade_atual} -> {destino['cidade']}")
        print(f"Distância: {destino['distancia']} km")
        print(f"Tempo: {destino['tempo']}")
        print()

        cidade_atual = destino["cidade"]


# -----------------------------------------------------
# Listar destinos
# -----------------------------------------------------
def listar_destinos():

    print("\n=== DESTINOS CADASTRADOS ===")

    for destino in rota:

        print(
            f"{destino['cidade']} - "
            f"{destino['distancia']} km - "
            f"{destino['tempo']}"
        )


# -----------------------------------------------------
# Cadastrar novo destino
# -----------------------------------------------------
def cadastrar_destino():

    nome = input("Nome da comunidade/cidade: ")

    while True:
        try:
            distancia = float(
                input("Distância até a próxima parada (km): ")
            )
            break # Sair do loop se a entrada for um número float válido
        except ValueError:
            print("Distância inválida. Por favor, insira um número (ex: 150 ou 2.5).")

    while True:
        tempo = input(
            "Tempo de viagem (hh:mm): "
        )
        try:
            # checar se o formato está correto.
            horas, minutos = tempo.split(":")
            int(horas)
            int(minutos)
            break # Sair do loop se o formato for válido
        except ValueError:
            print("Formato de tempo inválido. Por favor, use hh:mm.")

    rota.append({
        "cidade": nome,
        "distancia": distancia,
        "tempo": tempo
    })

    print("\nDestino cadastrado com sucesso!")


# -----------------------------------------------------
# Ordenar por distância (Bubble Sort)
# -----------------------------------------------------
def ordenar_por_distancia():

    n = len(rota)

    for i in range(n):

        for j in range(0, n - i - 1):

            if rota[j]["distancia"] > rota[j + 1]["distancia"]:

                rota[j], rota[j + 1] = (
                    rota[j + 1],
                    rota[j]
                )

    print("\nDestinos ordenados por distância!")

    listar_destinos()


# -----------------------------------------------------
# Distância total
# -----------------------------------------------------
def distancia_total():

    total = 0

    for destino in rota:

        total += destino["distancia"]

    print(
        f"\nDistância total da rota: {total} km"
    )

    return total


# -----------------------------------------------------
# Tempo total
# -----------------------------------------------------
def tempo_total():

    total_minutos = 0

    for destino in rota:

        total_minutos += converter_para_minutos(
            destino["tempo"]
        )

    print(
        "\nTempo total da rota:",
        converter_para_horas(total_minutos)
    )

    return total_minutos


# -----------------------------------------------------
# Comunidade mais distante
# -----------------------------------------------------
def destino_mais_distante():

    maior = rota[0]

    for destino in rota:

        if destino["distancia"] > maior["distancia"]:

            maior = destino

    print("\n=== DESTINO MAIS DISTANTE ===")

    print(
        f"{maior['cidade']} "
        f"({maior['distancia']} km)"
    )


# -----------------------------------------------------
# Simulação de chuva (+20%)
# -----------------------------------------------------
def simular_chuva():

    total_minutos = 0

    for destino in rota:

        total_minutos += converter_para_minutos(
            destino["tempo"]
        )

    total_chuva = int(total_minutos * 1.20)

    print("\n=== SIMULAÇÃO DE CHUVA ===")

    print(
        "Tempo normal:",
        converter_para_horas(total_minutos)
    )

    print(
        "Tempo com chuva:",
        converter_para_horas(total_chuva)
    )


# -----------------------------------------------------
# Menu Principal
# -----------------------------------------------------
while True:

    print("\n================================")
    print(" ORGANIZADOR DE ROTAS FLUVIAIS ")
    print("================================")
    print("1 - Listar rota")
    print("2 - Listar destinos")
    print("3 - Cadastrar destino")
    print("4 - Ordenar por distância")
    print("5 - Calcular distância total")
    print("6 - Calcular tempo total")
    print("7 - Destino mais distante")
    print("8 - Simular atraso por chuva")
    print("0 - Sair")

    opcao = input("\nEscolha uma opção: ")

    if opcao == "1":
        listar_rota()

    elif opcao == "2":
        listar_destinos()

    elif opcao == "3":
        cadastrar_destino()

    elif opcao == "4":
        ordenar_por_distancia()

    elif opcao == "5":
        distancia_total()

    elif opcao == "6":
        tempo_total()

    elif opcao == "7":
        destino_mais_distante()

    elif opcao == "8":
        simular_chuva()

    elif opcao == "0":
        print("\nSistema encerrado.")
        break

    else:
        print("\nOpção inválida!")